/* ===== Report UI: view + pdf generation ===== */
(function () {
  // helper template: render report HTML 
  function renderReportHtml(payload, filters) {
    // payload contains inward/outward aggregated metrics 
    const { month, year, office } = filters;
    function monthName(m) {
      return ["","January","February","March","April","May","June","July","August","September","October","November","December"][m] || "";
    }

    // build region rows for inward and outward
    function regionRows(obj) {
      // obj is { A: {...}, B: {...}, C: {...} } as present
      const keys = Object.keys(obj || {});
      return keys.map(k => `
        <tr>
          <td style="padding:8px;border:1px solid #eee">${k}</td>
          <td style="padding:8px;border:1px solid #eee;text-align:center">${obj[k].receivedEnglish||0}</td>
          <td style="padding:8px;border:1px solid #eee;text-align:center">${obj[k].repliedHindi||0}</td>
          <td style="padding:8px;border:1px solid #eee;text-align:center">${obj[k].repliedEnglish||0}</td>
          <td style="padding:8px;border:1px solid #eee;text-align:center">${obj[k].notExpected||0}</td>
        </tr>
      `).join("");
    }

    // Outward region rows
    function outwardRegionRows(obj) {
      const keys = Object.keys(obj || {});
      return keys.map(k => {
        const h = obj[k].hindi || 0;
        const e = obj[k].english || 0;
        const total = h + e;
        const perc = total ? Math.round((h / total) * 100) : 0;
        return `
          <tr>
            <td style="padding:8px;border:1px solid #eee">${k}</td>
            <td style="padding:8px;border:1px solid #eee;text-align:center">${h}</td>
            <td style="padding:8px;border:1px solid #eee;text-align:center">${e}</td>
            <td style="padding:8px;border:1px solid #eee;text-align:center">${total}</td>
            <td style="padding:8px;border:1px solid #eee;text-align:center">${perc}%</td>
          </tr>
        `;
      }).join("");
    }

    // top-level metrics
    const s = payload;
    return `
      <div id="reportHtml" style="font-family:Inter, Arial, sans-serif; color:#222;">
        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:12px;">
          <div>
            <h2 style="margin:0;">Quarterly Hindi Rajbhasha Report</h2>
            <div style="color:#666">${monthName(month)} ${year} ${office ? " | Office: " + office : ""}</div>
          </div>
          <div style="text-align:right; color:#666">
            <div>Generated by: <strong id="reportGeneratedBy">${document.getElementById("adminName")?.textContent || ""}</strong></div>
            <div>Date: ${new Date().toLocaleDateString()}</div>
          </div>
        </div>

        <hr style="border:none;border-top:1px solid #e6e6e6;margin:10px 0;">

        <h4>Section 1 — Letters Received in Hindi (Rule–5)</h4>
        <table style="width:100%; border-collapse:collapse; margin-bottom:10px;">
          <tr><td style="padding:8px;border:1px solid #eee">Total letters received in Hindi</td><td style="padding:8px;border:1px solid #eee">${s.lettersReceivedHindi||0}</td></tr>
          <tr><td style="padding:8px;border:1px solid #eee">Replies sent in Hindi</td><td style="padding:8px;border:1px solid #eee">${s.repliesSentHindi||0}</td></tr>
          <tr><td style="padding:8px;border:1px solid #eee">Replies sent in English</td><td style="padding:8px;border:1px solid #eee">${s.repliesSentEnglish||0}</td></tr>
          <tr><td style="padding:8px;border:1px solid #eee">Not expected to be replied</td><td style="padding:8px;border:1px solid #eee">${s.notExpectedTotal||0}</td></tr>
        </table>

        <h4>Section 2 — Letters Received in English but Replied in Hindi (Region-wise)</h4>
        <table style="width:100%; border-collapse:collapse; margin-bottom:10px;">
          <thead>
            <tr style="background:#f7f7f7">
              <th style="padding:8px;border:1px solid #eee">Region</th>
              <th style="padding:8px;border:1px solid #eee">Letters Received (English)</th>
              <th style="padding:8px;border:1px solid #eee">Replied in Hindi</th>
              <th style="padding:8px;border:1px solid #eee">Replied in English</th>
              <th style="padding:8px;border:1px solid #eee">Not Expected</th>
            </tr>
          </thead>
          <tbody>
            ${regionRows(s.inwardByRegion || {})}
          </tbody>
        </table>

        <h4>Section 3 — Letters Issued (Outward) (Region-wise)</h4>
        <table style="width:100%; border-collapse:collapse; margin-bottom:10px;">
          <thead>
            <tr style="background:#f7f7f7">
              <th style="padding:8px;border:1px solid #eee">Region</th>
              <th style="padding:8px;border:1px solid #eee">Issued in Hindi/Bilingual</th>
              <th style="padding:8px;border:1px solid #eee">Issued in English</th>
              <th style="padding:8px;border:1px solid #eee">Total Issued</th>
              <th style="padding:8px;border:1px solid #eee">% in Hindi/Bilingual</th>
            </tr>
          </thead>
          <tbody>
            ${outwardRegionRows(s.outwardByRegion || {})}
          </tbody>
        </table>

        <div style="margin-top:18px; display:flex; gap:20px;">
          <div>
            <strong>Total Inwards:</strong> ${s.totalInwards || 0}
          </div>
          <div>
            <strong>Total Outwards:</strong> ${s.totalOutwards || 0}
          </div>
        </div>

        <div style="margin-top:28px; display:flex; gap:20px; justify-content:flex-end;">
          <div style="text-align:center;">
            <div>Prepared By</div>
            <div style="height:60px; border-bottom:1px solid #ddd; margin-top:16px;"></div>
            <div style="color:#666; font-size:13px;">Name & Signature</div>
          </div>

          <div style="text-align:center;">
            <div>Group Head</div>
            <div style="height:60px; border-bottom:1px solid #ddd; margin-top:16px;"></div>
            <div style="color:#666; font-size:13px;">Name & Signature</div>
          </div>
        </div>
      </div>
    `;
  }

  async function fetchReportData(filters) {
    const body = JSON.stringify(filters);
    const res = await fetch("/admin/report/data", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "same-origin",
      body
    });
    if (!res.ok) {
      const j = await res.json().catch(()=>null);
      throw new Error((j && j.message) || "Failed to fetch report data");
    }
    return await res.json();
  }

  // render preview into container
  async function viewReport() {
    const month = Number(document.getElementById("reportMonth").value);
    const year = Number(document.getElementById("reportYear").value);
    const office = document.getElementById("reportOffice").value || "";

    if (!month || !year) return alert("Select month and year");

    const filters = { month, year, office };
    const container = document.getElementById("reportPreviewContainer");
    container.innerHTML = `<div style="padding:30px;text-align:center;color:#777">Loading report…</div>`;

    try {
      const data = await fetchReportData(filters);
      container.innerHTML = renderReportHtml(data, filters);
    } catch (err) {
      console.error("viewReport:", err);
      container.innerHTML = `<div style="padding:30px;text-align:center;color:#c00">${err.message}</div>`;
    }
  }

  // request server to create PDF; server will return a URL for download
  async function generatePdf() {
    const month = Number(document.getElementById("reportMonth").value);
    const year = Number(document.getElementById("reportYear").value);
    const office = document.getElementById("reportOffice").value || "";

    if (!month || !year) return alert("Select month and year");

    const payload = { month, year, office };

    try {
      const res = await fetch("/admin/report/pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "same-origin",
        body: JSON.stringify(payload)
      });
      if (!res.ok) {
        const j = await res.json().catch(()=>null);
        throw new Error((j && j.message) || "PDF generation failed");
      }

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Rajbhasha_Report_${payload.year}_${payload.month}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("generatePdf:", err);
      alert(err.message || "Failed to create PDF");
    }
  }

  // wire buttons
  document.addEventListener("DOMContentLoaded", () => {
    const viewBtn = document.getElementById("viewReportBtn");
    const pdfBtn = document.getElementById("downloadPdfBtn");
    if (viewBtn) viewBtn.addEventListener("click", viewReport);
    if (pdfBtn) pdfBtn.addEventListener("click", generatePdf);
  });
})();


document.addEventListener("DOMContentLoaded", () => {
  const yearSelect = document.getElementById("reportYear");
  if (!yearSelect) return;

  const currentYear = new Date().getFullYear();

  // Generate range: current year → 10 years back and 2 year future 
  for (let y = currentYear + 2; y >= currentYear - 10; y--) {
    const opt = document.createElement("option");
    opt.value = y;
    opt.textContent = y;
    yearSelect.appendChild(opt);
  }
});
